### ISSUE TITLE
crash sudden

### ISSUE THREAD

**Issue by lostopkk** [Globox1997/Dehydration#102]
I was playing when it suddenly crashed without me knowing, and it appeared that it was this mod in the log
crash report: https://mclo.gs/3vMN5u3
log: https://mclo.gs/i8uvIyy

**Comment by Globox1997** [comment]
Pls update to the latest version of dehydration

**Comment by lostopkk** [comment]
> Pls update to the latest version of dehydration

but it's the newest version

**Comment by lostopkk** [comment]
> Pls update to the latest version of dehydration

![image](https://user-images.githubusercontent.com/50776714/190927010-da6603a9-214c-471f-bd0a-b35bb28b920a.png)
it's inside the log

**Comment by Globox1997** [comment]
I see, the dynamiccrosshair mod has to update their compatibility with dehydration
would be great if you open an issue on their github.

**Comment by lostopkk** [comment]
> I see, the dynamiccrosshair mod has to update their compatibility with dehydration would be great if you open an issue on their github.

ok, thank you!

**Comment by Crendgrim** [comment]
I have updated to the new function signature in DynamicCrosshairCompat 1.4.1, which should fix this bug.
