### ISSUE TITLE
Bamboo Pump can only be used once?

### ISSUE THREAD

**Issue by MysticcX** [Globox1997/Dehydration#103]
In the latest update (1.3.0) The bamboo pumps can only be used once so you heave to craft new pumps each time. You have to break the pump to get the purified water bucket, flask, ect and doesn't drop the pump which makes the whole process really tedious. Being able to right click the bucket or flask would solve the problem.

Also this isn't much of an issue however although you can store purified water in copper cauldrons, its more worth it to store water either in your flasks or in the campfire cauldron as it holds more water. The bigger cauldron should hold up to 4 like the campfire cauldron or somewhere near double. This could be added into the config menu.

**Comment by Globox1997** [comment]
Removed requiring tool with [https://github.com/Globox1997/Dehydration/commit/f98ddf2096b809a854b0c600cc181cfac85b9765](https://github.com/Globox1997/Dehydration/commit/f98ddf2096b809a854b0c600cc181cfac85b9765) which makes the pump dropable.
Get the item back by shift right click :)
The idea with bigger cauldron might be a future update but isn't on my to do list currently.
