### ISSUE TITLE
Farmer's Delight change hydration

### ISSUE THREAD

**Issue by DrFiishy** [Globox1997/Dehydration#104]
So would it be possible to change the hydration level of the recipes or add an option for it? Ive tried changing the "stew_thirst_quench" and the "drinks_thirst_quench" but nothing seems to be changing.

**Comment by Globox1997** [comment]
Did you find a solution?

**Comment by DrFiishy** [comment]
Well i THOUGHT i did, but it seems only 1 drink gives the hydraition. So i messed around with a few other settings but still couldnt get it to work (just forgot to re-open the issue hehe)

**Comment by Globox1997** [comment]
Which version do you use?

**Comment by DrFiishy** [comment]
Using 1.3.1

Ill have a looksy at it later today to see which drinks from which modpack dont seem to work properly

EDIT: So from the modpack im using for now i can only find these 3 not working

Melon Juice -Farmers delight
Milk Bottle -Farmers delight
Hot Cocoa -Farmers delight

**Comment by Globox1997** [comment]
Added a datapack system. Mods which add thirst item might still have to add custom compatibility.
