### ISSUE TITLE
Wont let me purify with a furnace.

### ISSUE THREAD

**Issue by JokubasJar** [Globox1997/Dehydration#105]
I put a dirty water bottle in the furnace, add some coal, and nothing happens.

**Comment by ByteSix** [comment]
Same here.

**Comment by Globox1997** [comment]
Bottles have to be placed on top of a campfire but buckets can be put in the furnace

**Comment by Ritter888** [comment]
Hi there, I'm a Youtuber and would like to use your mod to demonstrate how to to make a fun and challenging experience in Minecraft. However I'm hoping to show that you can drink clean water by using primitive / basic means. Getting copper is too advanced if I could first just make a leather flask and somehow purify with just a campfire or furnace. 

I placed a "Bottle of Water" and a "Flask" both with unpure water (green colored drops) on the campfire and waited for a long time with no change.
I placed "Bucket of Water", "Bottle of Water" and a "Flask" in a furnace and it doesn't cook them.

Can you help me?
