### ISSUE TITLE
purified water turns into impurified in copper cauldron when picking up with flask

### ISSUE THREAD

**Issue by aichaun** [Globox1997/Dehydration#106]
when i get a purified water bucket with the bamboo pump, sometimes when i put it in the copper cauldron and then use my flask on it, my flask (it was empty before) is filled with impurified water. I didn't have it happen with iron flask, but i have with the diamond flask.

**Comment by Globox1997** [comment]
Which mod version do you use?

**Comment by shrekussy** [comment]
where do i even put the bamboo pump in? do i put it in water?

**Comment by aichaun** [comment]
> Which mod version do you use?

i'm using version 11 of medieval minecraft, which i believe uses 1.3.1 of dehydration

**Comment by Anabella00geek** [comment]
I have a friend that is having this problem.  I have watched it happen to him a lot on his youtube (redspecsgaming) videos. I don't have the issue at all I am playing the same modpack (Medieval mod).  I was checking to see if anyone knows what causes this.  The modpack authors on their discord say this is how the pack works and the water in the copper cauldron goes dirty like that. I don't believe that is how you made the mod to work.

**Comment by Acht-Neun-Drei** [comment]
I've also had the same issue, whenever I put purified water into a copper cauldron, in about 3 or 4 minutes it becomes impurified when picked up with any flask but immediately impurified when picked up with a diamond flask. I'm still using version 1.2.9 of the mod but based on the replies this issue still hasn't been fixed in later versions.

**Comment by Globox1997** [comment]
Seems like an incorrect behavior. Reopen if this still happens on the latest version.
