### ISSUE TITLE
[Suggestion] Compatibility with Things for fabric (specifically Bater Wucket for the Campfire Cauldron)

### ISSUE THREAD

**Issue by Frontear** [Globox1997/Dehydration#108]
The Bater Wucket is an infinite water bucket, to put it simply, and it unfortunately does not seem to work with the item. It would be a nice QoL change if it could work with it.

**Comment by Globox1997** [comment]
This sounds actually just op

**Comment by Frontear** [comment]
imo it doesnt sound any more op than having an infinite water source and refilling it. this just reduces one action.

**Comment by enmumne** [comment]
Would be nice to have compatibility with Kibe wooden buckets.

**Comment by Globox1997** [comment]
Have no plans to add compatibility to the bater wucket.
