### ISSUE TITLE
Unable to retrieve bucket

### ISSUE THREAD

**Issue by Sin-Kaine** [Globox1997/Dehydration#109]
After I use the bamboo pump to fill a bucket, I cannot retrieve the bucket without breaking the pump. I've had an empty hand, done shift left/right click, ctrl left/right click and still nothing. Also cannot transfer purified water  into  flask.

**Comment by Globox1997** [comment]
empty hand right click, or sneak empty hand right click doesn't work?

**Comment by Globox1997** [comment]
Reopen if it doesn't work like that
