### ISSUE TITLE
[Suggestion] Dehydrating Tags

### ISSUE THREAD

**Issue by ClockwerkKaiser** [Globox1997/Dehydration#110]
I'd like to suggest some additional tags for dehydrating fluids and foods. Similarly to what you already provide for hydrating items. 

The use case I have in mind is to apply thirst/dehydration to alcoholic drinks (such as those in Drink Beer) to mimic real life. 

Both a "standard" dehydrating tag and a stronger dehydrating tag would be ideal (for stronger alcoholic and highly salty items).

**Comment by Globox1997** [comment]
I am working on a datapack system for giving items hydration :) I think this will meet your suggestion

**Comment by Globox1997** [comment]
Datapack system is done. Check it out here: [https://github.com/Globox1997/Dehydration#datapacks-since-version-133](https://github.com/Globox1997/Dehydration#datapacks-since-version-133)
