### ISSUE TITLE
This mod crashes minecraft every time it tries to render a screen showing water bars on hydrating food

### ISSUE THREAD

**Issue by MDdiamondOrigin** [Globox1997/Dehydration#111]
Every time I hover over honey, stew or any other hydrating food with my cursor, the minecraft crashes. It says rendering screen error. I've tried to change config of dehydration and I've managed to solve this issue for stews and soups by setting "stew_thirst_quench" to 0, however this method didn't work for honey and I think it's because the "honey_quench" property doesn't work, please fix your mod. I'm using this mod for my modpack for my server and my friends are quite uncomfortable with the fact that the honey crashes their minecraft..

**Comment by Globox1997** [comment]
Post the latest log and crash report here as a file
