### ISSUE TITLE
can't change dehydration in nether in mod menu

### ISSUE THREAD

**Issue by RGAZN** [Globox1997/Dehydration#114]
I've managed to turn off overheating blur on mod menu but not the fast dehydration and thirst when you use flasks and copper caldrons. All settings to slow down amount of thirst taken be tick don't work ether. tried changing the hunger intead of dehydration but that doesn't seem to slow down thirst ether.

**Comment by liamblylod** [comment]
How'd you turn off overheating effect?

**Comment by Globox1997** [comment]
Reopen this issue at the EnvironmentZ repository.
