### ISSUE TITLE
Incompatible with 1.19.3

### ISSUE THREAD

**Issue by Hedwig7s** [Globox1997/Dehydration#115]

**Comment by Globox1997** [comment]
[https://fabricmc.net/2022/11/24/1193.html](https://fabricmc.net/2022/11/24/1193.html)

**Comment by Hedwig7s** [comment]
> https://fabricmc.net/2022/11/24/1193.html

I'm aware. Still, how bad is it? I mean I've seen alot of mods update within the week

**Comment by Globox1997** [comment]
Shouldn't be that hard, next couple weeks are exam time

**Comment by Hedwig7s** [comment]
> Shouldn't be that hard, next couple weeks are exam time

Fuck exams man

**Comment by ZekePolarisBSH** [comment]
Will 1.19.4 be made?

**Comment by Globox1997** [comment]
For now I decided to work on 1.19.2 and wait for 1.20

**Comment by ZekePolarisBSH** [comment]
Oh ok
