### ISSUE TITLE
can't translate

### ISSUE THREAD

**Issue by wsxiya** [Globox1997/Dehydration#117]
I want to translate the items into Chinese, but there are two items that cannot be translated
![J$%V3IBNI1T`X6FXM4R}JOU](https://user-images.githubusercontent.com/114494454/218314283-7d71ba7c-9711-46ca-9328-a22819bb42fa.png)
![MN21@LAGA`ULT)U5AE2CAGX](https://user-images.githubusercontent.com/114494454/218314288-26ec0049-a2f4-4f4c-88e9-24d722bb4e57.png)

**Comment by wsxiya** [comment]
![J$%V3IBNI1T`X6FXM4R}JOU](https://user-images.githubusercontent.com/114494454/218314318-c9428eb4-6de5-4cc4-93d6-7833e237ada3.png)

**Comment by Globox1997** [comment]
Added translatable with [https://github.com/Globox1997/Dehydration/commit/1fdff2ff3e569d5dbd2b47f57eb10a4072961a9d](https://github.com/Globox1997/Dehydration/commit/1fdff2ff3e569d5dbd2b47f57eb10a4072961a9d)
