### ISSUE TITLE
Add configs to disable giving Haste Effect on low Thirst Bar

### ISSUE THREAD

**Issue by JasdanVM** [Globox1997/Dehydration#119]
When the Thgirst Bar is low, the player receives the Haste Effect, which doesn't really makes much sense and encourages being dehydrated, also add config to change the effect for something else, like Miner's Fatigue for example.

**Comment by Globox1997** [comment]
Added a config setting with [https://github.com/Globox1997/Dehydration/commit/f66bd67fb32b749fd95eb2625aa3accff47d0116](https://github.com/Globox1997/Dehydration/commit/f66bd67fb32b749fd95eb2625aa3accff47d0116)
