### ISSUE TITLE
Crashes on 1.19.4?

### ISSUE THREAD

**Issue by Chris-Creates** [Globox1997/Dehydration#120]
No crash report or anything, just error code 1. Using the latest version of the mod, fabric, cloth, and the game, and no other mods. The game just wont run :(

**Comment by goose-vii** [comment]
I'm having this issue as well, running the 1.19.2 jar file with a 1.19.4 Fabric installation.

**Comment by Globox1997** [comment]
No plans to update to 1.19.4. Working on 1.20.1 from now.
