### ISSUE TITLE
Getting water from river biome in flask becomes pure but other biomes stay dirty

### ISSUE THREAD

**Issue by Acht-Neun-Drei** [Globox1997/Dehydration#121]
I've had an issue where if I obtain water in a flask from a water source block in a river biome, it will instantly be pure, while in any other biome with a water source block it will be dirty. I have a feeling that this is not an intentional feature, and seems to be similar to the other issue raised by user aichaun (case number #106 )
thanks.

**Comment by Globox1997** [comment]
This is intentionally.
