### ISSUE TITLE
rapid dehydration in hot biomes

### ISSUE THREAD

**Issue by dull4h4n** [Globox1997/Dehydration#122]
I just wondered if we had a way to reduce the amount of dehydration in places like the desert. As is you have to drink about every 60 seconds, which I personally find unreasonable. Any way to reduce this in one of your mods?  Having trouble finding those settings.

**Comment by Globox1997** [comment]
You can adjust the hydration amount in hot biomes in the environmentz config.
Got probably adjusted in a later version.
