### ISSUE TITLE
1.20 crash upon campfire cauldron placement

### ISSUE THREAD

**Issue by HackermanCabinet** [Globox1997/Dehydration#124]
### Minecraft Version

1.20.x

### Mod Loader Version

0.83.0

### Mod Version

the 1.20 one

### Describe the Issue

When I am recording with Outplayed, and I place a Campfire Cauldron on a campfire, it crashes the game

### latest.log

[latest.log](https://github.com/Globox1997/Dehydration/files/11874000/latest.log)

### Do you use any other mods except the required ones?

I believe it is exclusively between this mod and Outplayed. I tested it with just the mod (and cloth-config) and fabric, and that's it. It still only crashed upon using Outplayed.

**Comment by ButterMe8aby** [comment]
Happens to me too, on a rather large modpack but with the bamboo pump. Upon placing it into water I get this crash.

[crash-2023-06-29_04.32.54-client.txt](https://github.com/Globox1997/Dehydration/files/11903682/crash-2023-06-29_04.32.54-client.txt)

Here's the log too: 
[latest.log](https://github.com/Globox1997/Dehydration/files/11903685/latest.log)

**Comment by Globox1997** [comment]
This got fixed in a later update.

**Comment by HackermanCabinet** [comment]
rad
