### ISSUE TITLE
Purified water is considered equal to plain water

### ISSUE THREAD

**Issue by TropheusJ** [Globox1997/Dehydration#126]
### Minecraft Version

1.19.x

### Mod Loader Version

loader 0.14.19, API 0.73.2+1.19.2

### Mod Version

1.3.4

### Describe the Issue

WaterFluidMixin makes plain water match purified water [here](https://github.com/Globox1997/Dehydration/blob/6c1c075468a80c1d4de707e5c5f704060a82031f/src/main/java/net/dehydration/mixin/WaterFluidMixin.java#L35).

This is causing Create's filling recipes using water to break. See the original issue here for details: https://github.com/Fabricators-of-Create/Create/issues/983

Plain water is matching the purified water, magically converting it when filling.

### latest.log

note: from a dev env
https://gist.github.com/TropheusJ/5a57fdf4726068040ff91032104d138e

### Do you use any other mods except the required ones?

Create

**Comment by Globox1997** [comment]
This mixin is required for a couple reasons not sure what would happen if I disable it when Create is loaded? But I guess this is the only fix?

**Comment by Globox1997** [comment]
Added a create check with [https://github.com/Globox1997/Dehydration/commit/25336a68be08e440d2813651fd2e0b6a2c6c210e](https://github.com/Globox1997/Dehydration/commit/25336a68be08e440d2813651fd2e0b6a2c6c210e)
This should fix the issue.
