### ISSUE TITLE
Unable to get Y-rotated facing of down

### ISSUE THREAD

**Issue by Niz09090** [Globox1997/Dehydration#127]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.21 fabric

### Mod Version

1.3.4

### Describe the Issue

when I try to place couldron from above or slightly above game crashes

### latest.log

https://paste.atlauncher.com/view/9886825a-9be0-4166-b81d-5d9c4a8689bd

**Comment by LReaper31** [comment]
Up, same issue, plus the bamboo pump 

Error: java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to up on Block{dehydration:bamboo_pump}, it is not an allowed value

**Comment by Globox1997** [comment]
Got fixed.
