### ISSUE TITLE
1.20.1 planned?

### ISSUE THREAD

**Issue by Therkelsen** [Globox1997/Dehydration#128]
### Make sure you are not opening a duplicate.

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Hey!

Is a 1.20.1 update planned?

**Comment by pete-h** [comment]
https://github.com/Globox1997/Dehydration/pull/133
I created a fork and pull request, that brings the mod to 1.20.1
Maybe someone sees and merges it.

**Comment by pete-h** [comment]
@Therkelsen as I just saw, @Globox1997 just updated to 1.20.1 :)
