### ISSUE TITLE
Option to disable the "appleskin" features.

### ISSUE THREAD

**Issue by Mabra51** [Globox1997/Dehydration#129]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Having the option to disable the preview of how much thirst you'll get and the thirst tooltips would be nice to make it fit with the vanilla hunger bar.

The tooltips also don't update if you change the thirst values in the mod options.

**Comment by emoandproud** [comment]
This would be a really nice feature to have!

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/Dehydration/commit/b8a14a2cd390696992f442ae98cc1f4e0a03926b](https://github.com/Globox1997/Dehydration/commit/b8a14a2cd390696992f442ae98cc1f4e0a03926b)
