### ISSUE TITLE
Filling a flask should remove the water block.

### ISSUE THREAD

**Issue by RDKRACZ** [Globox1997/Dehydration#13]
So when you want to fill a netherite leather flask you need 3 water blocks.

**Comment by RDKRACZ** [comment]
Can you add an option to disable flasks other than leather one?

**Comment by Globox1997** [comment]
Actually very good idea to remove the water source block, otherwise it's basically too easy to get water but some people have talked about a water purification system, haven't got a good solution yet. Why do you want to disable the other flasks?

**Comment by RDKRACZ** [comment]
Diamond and netherite flasks feel too op imo. You can fill it once and it will refill your thirst bar (I don’t remember defaults) like nearly 2 times. The flask would need to be super big to archive this (yea I know this is just Minecraft). I don’t like this for the same reason I don’t like upgradable chests/furnaces.
Idk if this was in tough as nails or somewhere else but there was an item called filter. You crafted it from sand, maybe gravel and maybe a few strings? If used with a water bottle (or flask) it would purify the water inside. Water taken from the source should have about 40% chance to poison you.

**Comment by Globox1997** [comment]
Thought about it twice and since a bottle doesn't remove the source block, the flask shouldn't do it either but I will still think about the purification system
