### ISSUE TITLE
[Datapack]Did not run as expected

### ISSUE THREAD

**Issue by DavidBlackCN** [Globox1997/Dehydration#132]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

1.3.4

### Describe the Issue

I am trying to provide compatibility for some vanilla and moded foods through datapacks,but it doesn't seem to work exactly as expected.

Some values of the food were not loaded into the game.
I tierd [vanilla],[farmers-delight-fabric-1.19.2-1.3.10],[Adorn-3.9.1+1.19.2-fabric](For its drinks).
All values for vanilla are loaded ,
Some values for farmers-delight are out loaded(Some are loaded).
All values for adorn are out loaded.

Example for adorn:
![1](https://github.com/Globox1997/Dehydration/assets/111333777/28826969-055f-45fd-a590-3e14895e8c9b)

but got nothing:
![2](https://github.com/Globox1997/Dehydration/assets/111333777/c3c5814c-ea8b-4568-ba5b-3056a35424ff)

Mod list:
RoughlyEnoughItems-9.1.632
farmers-delight-fabric-1.19.2-1.3.10
dehydration-1.3.4
Adorn-3.9.1+1.19.2-fabric
architectury-6.5.85-fabric
cloth-config-8.3.103-fabric
fabric-api-0.76.0+1.19.2
fabric-language-kotlin-1.10.0+kotlin.1.9.0

Is this a bug of the mod(datapack system),or just a mistake of my datapack/cilent?

### latest.log

Not mention.

### Do you use any other mods except the required ones?

as above

**Comment by Globox1997** [comment]
Some items might need custom compatibility.

**Comment by Globox1997** [comment]
So as I wrote, some items need custom compatibility, dehydration provides an api to do so.
