### ISSUE TITLE
I can't tell if this is a bug or not

### ISSUE THREAD

**Issue by DevoDude** [Globox1997/Dehydration#135]
### Minecraft Version

1.20.x

### Mod Loader Version

[1.20.1] Fabric API 0.86.1+1.20.1

### Mod Version

dehydration-1.3.4+1.20

### Describe the Issue

When I place my bamboo pump and pump water into it, it gives me purified water, like it should. Then after placing it into a copper cauldron and adding it to my flask, when I drank it, it gave me thirst like it was impure water. Does the bamboo pump not work after picking it up and moving it or something?

### latest.log

I can't find it

### Do you use any other mods except the required ones?

medieval mod pack

**Comment by Globox1997** [comment]
Can not reproduce this bug. Check the tooltip of the flask if it is impurified.
