### ISSUE TITLE
Book Not Loaded

### ISSUE THREAD

**Issue by lucasteo16** [Globox1997/Dehydration#142]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.23

### Mod Version

1.3.4+1.20.1

### Describe the Issue

Book not craftable and not given to player when starting a new game. (I do not know what the default behavior is)

### latest.log

Extracted Logs
```
[10:33:06] [Render thread/ERROR]: Failed to load book dehydration:dehydration defined by mod dehydration, skipping
java.lang.IllegalArgumentException: Book dehydration:dehydration has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
```

### Do you use any other mods except the required ones?

yes

**Comment by TrollingDEAD** [comment]
+1

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/Dehydration/commit/88e67485745d374488d9ea2f9837c0518b339b99](https://github.com/Globox1997/Dehydration/commit/88e67485745d374488d9ea2f9837c0518b339b99)
Just have not published yet.
