### ISSUE TITLE
[Feature Request] Add a wooden pot or a wooden flask that allows you to drink water

### ISSUE THREAD

**Issue by Heus-Sueh** [Globox1997/Dehydration#143]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

In some modpacks, finding leather to make the flask is difficult or almost impossible in some seeds, my suggestion would be a wooden pot that allows you to collect water and drink it, but you have a very high chance of getting poisoned like eating a rotten potato, but you would regain your thirst little by little.
![image](https://github.com/Globox1997/Dehydration/assets/98482469/c46a71e9-afd6-48a4-98e2-9e14c9c30fc6)

or a wooden bottle in this square shape, or a more round shape.
![image](https://github.com/Globox1997/Dehydration/assets/98482469/ebb56a30-726d-4f0b-a067-89651f3f039f)

**Comment by Globox1997** [comment]
You can drink water by sneak+hold right key while looking at water.

**Comment by Globox1997** [comment]
Added a water bowl with [https://github.com/Globox1997/Dehydration/commit/74ad13c4a0bfe28ec33ba84e5d896035205d6ca1](https://github.com/Globox1997/Dehydration/commit/74ad13c4a0bfe28ec33ba84e5d896035205d6ca1)
