### ISSUE TITLE
exit code1 with dehydration

### ISSUE THREAD

**Issue by githubaccountaccount** [Globox1997/Dehydration#144]
### Minecraft Version

1.20.x

### Mod Loader Version

1.21

### Mod Version

1.3.4

### Describe the Issue

I have Cloth Config API and Fabric API but whenever I put dehydration in the mods folder it comes up with exit code 1 but when i take it out I can launch Minecraft I need an explanation because it should be compatible with fabric

### latest.log

[latest.log](https://github.com/Globox1997/Dehydration/files/13327582/latest.log)

### Do you use any other mods except the required ones?

sodium, lithium and iris shaders+ the configs and apis

**Comment by Globox1997** [comment]
This is due to environmentz, update to the latest version.
