### ISSUE TITLE
Bamboo Pump Cooldown Bypass

### ISSUE THREAD

**Issue by Cicopath** [Globox1997/Dehydration#157]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.7

### Mod Version

1.3.5

### Describe the Issue

The cooldown for the Bamboo Pump can be bypassed by simply breaking the block and placing it back down.

### latest.log

N/A (I'll get a fresh log without any other mods but the necessary ones later.)

### Do you use any other mods except the required ones?

Yes.

**Comment by Globox1997** [comment]
Fixed cooldown with [https://github.com/Globox1997/Dehydration/commit/233b896b4e19c91458c57e3c525f0d067082da3b](https://github.com/Globox1997/Dehydration/commit/233b896b4e19c91458c57e3c525f0d067082da3b)
