### ISSUE TITLE
Don't allow sprinting when thirst is below 6 points; Don't regenerate health when thirst is below 18 points.

### ISSUE THREAD

**Issue by RDKRACZ** [Globox1997/Dehydration#17]
To mimic vanilla food behavior.

**Comment by Globox1997** [comment]
Good idea :) Somebody gave me this suggestion already but I forgot it^^

**Comment by Globox1997** [comment]
done [https://github.com/Globox1997/Dehydration/commit/7ea2aab8eb893dd01055361e21a8db23e47d524f](https://github.com/Globox1997/Dehydration/commit/7ea2aab8eb893dd01055361e21a8db23e47d524f)
