### ISSUE TITLE
Water Bar still appears in Spectator Mode

### ISSUE THREAD

**Issue by TheDeathlyCow** [Globox1997/Dehydration#174]
### Minecraft Version

1.21.x

### Mod Loader Version

0.15.11

### Mod Version

1.3.6

### Describe the Issue

While testing out Scorchful's Dehydration integration on 1.21, I noticed that the water bar still appears on the HUD when in spectator mode. I'm assuming this isn't intended, as the bar does not show in creative mode. From analysis of the code, I think this line is all the needs to be updated with something like an `isSpectator()` check. 

https://github.com/Globox1997/Dehydration/blob/c5554f63430f6b03b8a35f98ba5bb401d29a7496/src/main/java/net/dehydration/thirst/ThirstHudRender.java#L30

### latest.log

[latest.log](https://github.com/user-attachments/files/16190204/latest.log)
![image](https://github.com/user-attachments/assets/813f083b-ccd8-472d-bc05-235b2afe33a8)

### Do you use any other mods except the required ones?

Scorchful, Thermoo, Mod Menu, Satin, Cardinal Components API

**Comment by cech12** [comment]
I think that will be fixed with #171

https://github.com/Globox1997/Dehydration/pull/171/files#diff-20b0f3c8529285fd4a9c9a76220881f9e032a7f0e38fb7fec66aba9ad3ee5ea4R30

**Comment by TheDeathlyCow** [comment]
Yeah that PR looks like it should fix it. I must've missed it, sorry.

**Comment by Globox1997** [comment]
Fixed with the update.
