### ISSUE TITLE
Shift+Right click water block with empty hand to take a sip.

### ISSUE THREAD

**Issue by RDKRACZ** [Globox1997/Dehydration#18]
This should restore 1 thirst point. Useful when you don't have any bottles in the inventory.

**Comment by RDKRACZ** [comment]
Currently, it's hard to not run out of the thirst bar and die at the start of the new world because it's not easy to craft a glass bottle or find and milk a cow. This feature would easier the beginning stage of the game (still harder than vanilla so it's okay). For now, players are using bonus chest as you adviced.

**Comment by Globox1997** [comment]
Got requested multiple times, thought about it a lot and now I added it [https://github.com/Globox1997/Dehydration/commit/90b5365c7126572a162453987d9b1ee36d91c1fe](https://github.com/Globox1997/Dehydration/commit/90b5365c7126572a162453987d9b1ee36d91c1fe)
