### ISSUE TITLE
Game crashed possibly because of Dehydration

### ISSUE THREAD

**Issue by GitUser14975** [Globox1997/Dehydration#181]
### Minecraft Version

1.21.x

### Mod Loader Version

0.16.0

### Mod Version

dehydration-1.3.6.jar

### Describe the Issue

The game crashed randomly when I was in a village, shortly after the world has been created.

There are both dehydration and indium mentioned in the crash log, so I thought it could be one of these two mods.

### latest.log

https://gist.github.com/TenKotowsky/d9e53293a9d30b5906ba6cae4609d06d
https://gist.github.com/TenKotowsky/41e3157a6f4730ce343498a4fbb54e4a

**Comment by cech12** [comment]
looks the same like #169 and should be fixed in #171

**Comment by Globox1997** [comment]
Yes should be fixed with the latest update. Reopen if not.
