### ISSUE TITLE
when making purified water in furnace the bucket duplicates

### ISSUE THREAD

**Issue by Apinoita** [Globox1997/Dehydration#182]
### Minecraft Version

1.20.x

### Mod Loader Version

quilt 0.26.0 with qfapi-7.6.0 qsl-6.2.0 fapi-0.92.2

### Mod Version

1.3.6

### Describe the Issue

when making purified water in furnace the water bucket becomes a normal bucket and a purified water bucket appears in the smelted slot thus a new bucket has appeared.

### latest.log

.

**Comment by Apinoita** [comment]
If its just a problem on my end let me know

**Comment by Apinoita** [comment]
also a I use lots of other mods but I don't think they are the issue with this

**Comment by Globox1997** [comment]
Should probably fixed in the 1.21 mc version of the mod.
Out of time reasons I only work on the latest version of my mods.

**Comment by Apinoita** [comment]
oh ok
