### ISSUE TITLE
Option to disable flasks other than leather one.

### ISSUE THREAD

**Issue by RDKRACZ** [Globox1997/Dehydration#20]
Flask is a flask :)
Maybe it's just me but I feel like the "stronger flasks" are too op.

**Comment by Globox1997** [comment]
if you feel like those are op, you can set down the value of the flasks in settings :)

**Comment by RDKRACZ** [comment]
Since there is no way to set flasks thirst values individually I can't nerf them (without breaking the basic leather one, which shouldn't be nerfed). I can only disable their recipes via datapack but they can still be acquired in other ways.
They are op because of their capacity. Why making something the same way but adding e.g. diamonds to it makes it better? They are good for players who like mods like [Iron Chests](https://www.curseforge.com/minecraft/mc-mods/iron-chests) because this is the same idea but for those liking some more realism (which Dehydration is trying to add with the thirst) they are bad. I think https://github.com/Globox1997/Dehydration/issues/19 is a better idea but that's up to you.

**Comment by Globox1997** [comment]
Yes the upgraded flasks have a big capacity but the mod is not there to annoy the player too much by saying: drink, drink more and fill up your bottle every other minute :)

**Comment by Globox1997** [comment]
As far as I know this can be done via datapacks or kubejs :)
