### ISSUE TITLE
Water purification system.

### ISSUE THREAD

**Issue by RDKRACZ** [Globox1997/Dehydration#21]
Water taken directly from the water block should have a chance (~50%) to poison the player.
To purify the water you can:
- use a charcoal filter - https://rlcraft.fandom.com/wiki/Charcoal_Filter
- boil water bottle in the furnace or campfire and receive a new item - "Purified Water Bottle" - it should have 1 thirst point lower than water bottle since you know, water boils, etc.

Another idea is to add a new block - Water Purification Station or Water Filter - crafted with sand, gravel, and some cobblestone - where you can put up to 3 bottles, like in the Brewing Stand, and purify the water, but it should take some time (20 seconds?)

This is how it looks it some other mod
![image](https://user-images.githubusercontent.com/43277609/113756675-f70d1500-9711-11eb-961a-8864cd8a6c2d.png)

**Comment by Globox1997** [comment]
requested and talked about on curseforge a lot and now added a purification system :) [https://github.com/Globox1997/Dehydration/commit/592837b4a2fd09a7be71995a2db3e414654f1c2a](https://github.com/Globox1997/Dehydration/commit/592837b4a2fd09a7be71995a2db3e414654f1c2a)
