### ISSUE TITLE
Apply Mining Fatigue when both thirst and food bar are empty.

### ISSUE THREAD

**Issue by RDKRACZ** [Globox1997/Dehydration#22]
Slowness is also a good option.

**Comment by RDKRACZ** [comment]
And Nausea.

**Comment by RDKRACZ** [comment]
Or you can make it a new status effect called Tiredness or Empry Stomach which would have these effect all in one to not spam the GUI like me now this issue.

**Comment by Globox1997** [comment]
Nice idea, didn't add nausea and slowness cause the player should still have the chance to safe him self[https://github.com/Globox1997/Dehydration/commit/c9a25f7073c96048b311039e3d57f139408f2cc3](https://github.com/Globox1997/Dehydration/commit/c9a25f7073c96048b311039e3d57f139408f2cc3)
