### ISSUE TITLE
Sleeping depletes thirst bar.

### ISSUE THREAD

**Issue by RDKRACZ** [Globox1997/Dehydration#23]
When waking up the players should be a little thirsty, maybe like -4 points from before the sleep?

**Comment by Globox1997** [comment]
Awesome idea, added it [https://github.com/Globox1997/Dehydration/commit/dc1ba65ebad7a1166bb6a12dfde678d7ae93d4b5](https://github.com/Globox1997/Dehydration/commit/dc1ba65ebad7a1166bb6a12dfde678d7ae93d4b5)

**Comment by RDKRACZ** [comment]
Could you please do the same with hunger? It would then be consistent and logical.

**Comment by Globox1997** [comment]
When you check the commit, the players hunger gets reduced too but only the half of the thirst :)
Will add a config

**Comment by RDKRACZ** [comment]
Ohh that's really good, was at work so I only had time to write a comment.
