### ISSUE TITLE
Compatibility with Puddles mod.

### ISSUE THREAD

**Issue by RDKRACZ** [Globox1997/Dehydration#24]
When using a flask on a puddle it isn't disappearing like when using a glass bottle. This is related to https://github.com/Globox1997/Dehydration/issues/13. The flask shouldn't be filled up from just one puddle. Please albo consider disabling the ability to fill up a flask from a puddle since there's not much water in it.

**Comment by Globox1997** [comment]
What happens if you use a bucket on a puddle? the flask can be used and gets filled without removing the puddle?

**Comment by RDKRACZ** [comment]
>What happens if you use a bucket on a puddle? 

Nothing as it should.

>The flask can be used and gets filled without removing the puddle?

Yes

How to give an empty flask? This gives an already filled one.
![image](https://user-images.githubusercontent.com/43277609/114185014-82222100-9945-11eb-90b1-6a4c530b307f.png)

**Comment by Globox1997** [comment]
Added puddle compat [https://github.com/Globox1997/Dehydration/commit/c73eeb881192532b59bf99d2fcd5929acf48a02e](https://github.com/Globox1997/Dehydration/commit/c73eeb881192532b59bf99d2fcd5929acf48a02e) you have to add nbt tag
