### ISSUE TITLE
Thirst Glitch using Flask.

### ISSUE THREAD

**Issue by orznick14** [Globox1997/Dehydration#28]
If impurified water is drank from a flask, thirst visually lasts until leaving and opening the world again. Hydration seems to drain at the same rate, and effect is stuck at 00:00 when this happens. This does not happen when drinking impurified water from a glass bottle. Effect does not go away with time or after drinking purified water.

**Comment by Globox1997** [comment]
Fixed it [https://github.com/Globox1997/Dehydration/commit/b3f83d2ba7226d4087103a54517555fad6c12286](https://github.com/Globox1997/Dehydration/commit/b3f83d2ba7226d4087103a54517555fad6c12286)
