### ISSUE TITLE
switching dimensions visually glitches the thirst bar 

### ISSUE THREAD

**Issue by Nachtalb** [Globox1997/Dehydration#32]
After using teleporting to another dimension (eg. with mods like https://www.curseforge.com/minecraft/mc-mods/fabrichomes and https://www.curseforge.com/minecraft/mc-mods/fabricwarps) the thirst bar indicates "full" even tho it is not. In the video I made for https://github.com/CodedSakura/FabricWarps/issues/2 it can be seen at timestamps 00:00 (overworld) compared to 00:06 (end) and at the end (overworld) when drinking it reapers correctly 01:03: 

https://user-images.githubusercontent.com/9467802/122257640-808a5180-ced0-11eb-8511-7a90bce76585.mp4 

Example fix for status effects and exp bar from the tp mod as reference: https://github.com/CodedSakura/FabricWarps/issues/2#issuecomment-862627165 https://github.com/CodedSakura/FabricCrossDimTPFix/blob/master/src/main/java/eu/codedsakura/fabriccrossdimtpfix/mixin/TPMixin.java

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/Dehydration/commit/def98790b56729746c67ce87496efa9ba1f5ace3](https://github.com/Globox1997/Dehydration/commit/def98790b56729746c67ce87496efa9ba1f5ace3)
Thanks for reporting

**Comment by ashtneoi** [comment]
Will the fix be backported to Minecraft 1.16? (It's okay if not.)

**Comment by Globox1997** [comment]
No plans to work on older versions
