### ISSUE TITLE
Nether faster thirsty

### ISSUE THREAD

**Issue by Nachtalb** [Globox1997/Dehydration#33]
IMHO it would make sense to get thirsty faster in the nether due to the heat :)

**Comment by Globox1997** [comment]
Added a config setting for it [https://github.com/Globox1997/Dehydration/commit/8aee943ce2230b9c6984922741dbe1256d0ed5be](https://github.com/Globox1997/Dehydration/commit/8aee943ce2230b9c6984922741dbe1256d0ed5be)
For now I will keep it by default to false, may change it in the future
