### ISSUE TITLE
some functionality to prepare and auto fill purified water

### ISSUE THREAD

**Issue by Nachtalb** [Globox1997/Dehydration#34]
It'd be nice to have a way to get filled flasks automatically. This could be made eg. by putting the fire under a cauldron (if purifying water would be possible with a normal Minecraft cauldron that is) and then add the ability to fill the flasks with a dispenser. Or fill the campfire cauldron via a dispenser. 

I really like the thirst functionality itself. It's just a bit annoying that you always have to go back home to fill the campfire cauldron manually and then painstakingly fill the flask again and again. It's good for the start of the game but gets a bit annoying towards the endgame.

**Comment by Globox1997** [comment]
Added interaction between the campfire cauldron and the dispenser :)
Now the cauldron can get filled up with water by water buckets and flasks can get filled with boiled water 
[https://github.com/Globox1997/Dehydration/commit/2d635dc4d7ea92577179dbe7b2d00f7851c6d192](https://github.com/Globox1997/Dehydration/commit/2d635dc4d7ea92577179dbe7b2d00f7851c6d192)
