### ISSUE TITLE
API for other mods

### ISSUE THREAD

**Issue by Madis0** [Globox1997/Dehydration#35]
Could you add an API or some kind of instructions for other mods that could integrate with this? For example, getting the thirst level or adding new flasks.

**Comment by Globox1997** [comment]
Should be pretty simple cause I use an interface to get the thirstmanager which can be found here:
[https://github.com/Globox1997/Dehydration/blob/master/src/main/java/net/dehydration/access/ThristManagerAccess.java](https://github.com/Globox1997/Dehydration/blob/master/src/main/java/net/dehydration/access/ThristManagerAccess.java)
New flasks can get added easily when using the Leather_Flask class like I do in the ItemInit class:
public static final Leather_Flask DIAMOND_LEATHER_FLASK = register("diamond_leather_flask", new Leather_Flask(3, new Item.Settings().group(ItemGroup.MISC).maxCount(1)));
