### ISSUE TITLE
There is no UI in the game. I don't know if that's the problem

### ISSUE THREAD

**Issue by wfwfwfw** [Globox1997/Dehydration#36]
![image](https://user-images.githubusercontent.com/72644389/123532444-a371fc80-d73f-11eb-9478-9ad30fa24b37.png)
![P{_$T 4Q{Z5V6GJ%(RT$I1U](https://user-images.githubusercontent.com/72644389/123532466-de743000-d73f-11eb-98fe-2e2a81cf1b2a.png)
[crash-2021-06-27_10.55.01-client.txt](https://github.com/Globox1997/Dehydration/files/6720999/crash-2021-06-27_10.55.01-client.txt)

**Comment by Globox1997** [comment]
looks like a mod incompatibility, my guess is your hud mod causes this issue?

**Comment by Globox1997** [comment]
Probably fixed with [https://github.com/Globox1997/Dehydration/commit/4c0f62f1bbf1932407365ba780244b8c5f46d952](https://github.com/Globox1997/Dehydration/commit/4c0f62f1bbf1932407365ba780244b8c5f46d952)
