### ISSUE TITLE
UI interference

### ISSUE THREAD

**Issue by Adarrack** [Globox1997/Dehydration#39]
I guess one of my mods is interfering with the UI for your mod. I can drink, get thirsty, and all the other parts work but I don't get the UI and I don't know what is messing it up. I'm using a modified version of the Medieval Minecraft 1.17 modpack. The differences being mods obviously. But as far as I know nothing should be conflicting with your mod and it worked the first few times I ran the pack but now it just doesn't. No crash or anything.

**Comment by Globox1997** [comment]
As long as I don't know which mod causes hud rendering trouble I can't really do something.
If you check which mod interferes with the thirst ui I will look further into it

**Comment by Globox1997** [comment]
Probably fixed with [https://github.com/Globox1997/Dehydration/commit/4c0f62f1bbf1932407365ba780244b8c5f46d952](https://github.com/Globox1997/Dehydration/commit/4c0f62f1bbf1932407365ba780244b8c5f46d952)
Reopen if necessary
