### ISSUE TITLE
Compat Issues with Requiem, Balance Issue with Origins

### ISSUE THREAD

**Issue by Cluelesshobo** [Globox1997/Dehydration#4]
With the mod [Requiem](https://www.curseforge.com/minecraft/mc-mods/requiem) installed, when you become undead the hunger bar is hidden, but hydration bar isnt. You dont need to drink as undead, so this is a cosmetic issue.

With the mod [Origins](https://www.curseforge.com/minecraft/mc-mods/origins), you have the option to start the game in the nether. With the mod Better Nether combined with 1.16 nether, starting in the nether isnt a bad idea for these players. The lack of any way to get water to drink might deadlock players in to repeatedly dying over and over. 
(The solution for this i'm not sure about other than not using the mod. Maybe be able to drink out of some plants from the better nether mod and 1.16? Maybe hotfix it by disabling hydration for the origins that start in the nether?)

**Comment by Globox1997** [comment]
The requiem compat may not to hard to do actually, don't know if I'm gonna add it in the future.
Never thought about starting in the nether which why it's good that you mentioned it here.
For now I also don't have a good idea how to solve it other than not using this mod, if I get an idea, I may add a way to get hydrated there

**Comment by SFort** [comment]
<details>
<summary><s>idea</s></summary>
you could disable thirst if they spawn in the neather

re-enable it perminantly as soon as they are in any other dim.(Optionally)

It is a bit of a hack that would have issues in edge cases with other mods tho so..
</details>
your best bet is implementing an API to disable thirst,

then transfer the issue to Origins and let them handle it.

As for the water in the neather maybe crying obsidian?

**Comment by Globox1997** [comment]
In the latest update I added a food hydration tag + stew hydration which is a way in the nether to stay hydrated :)

**Comment by Globox1997** [comment]
@Cluelesshobo 
Would you test a requiem compat version?

**Comment by Globox1997** [comment]
added requiem compat [https://github.com/Globox1997/Dehydration/commit/8729ce9a656f7dc19e437400678cfe00c96bde41](https://github.com/Globox1997/Dehydration/commit/8729ce9a656f7dc19e437400678cfe00c96bde41) and you can turn of the thirst effect for specific players by adding them to a list in the config

**Comment by RDKRACZ** [comment]
Hi, seems like this compat stopped working
![image](https://user-images.githubusercontent.com/43277609/117504942-83b22980-af83-11eb-84c5-4be8075d7984.png)

**Comment by RDKRACZ** [comment]
Also, when possessing a mob the hydration icons are overlapping the "oxygen" icons
![image](https://user-images.githubusercontent.com/43277609/117506818-819d9a00-af86-11eb-9156-3800144a59f0.png)
