### ISSUE TITLE
Campfire cauldron deletes water bottles

### ISSUE THREAD

**Issue by CrimsonDawn45** [Globox1997/Dehydration#42]
If you fill the campfire cauldron with a stack of water bottles in your hand it deletes the stack and replaces it with a single empty water bottle.

**Comment by Globox1997** [comment]
Should be the same as [https://github.com/Globox1997/Dehydration/issues/38](https://github.com/Globox1997/Dehydration/issues/38)

**Comment by CrimsonDawn45** [comment]
Sorry, I assumed bottle stacking was a vanilla feature but apparently I had some random mod installed somewhere that added it.
