### ISSUE TITLE
Crash with Dispensers

### ISSUE THREAD

**Issue by chronosacaria** [Globox1997/Dehydration#43]
Hi Globox_Z,

I hope you are well! I found a crash with dispensers with Dehydration. If you set up two tripwire hooks with string and a dispenser to receive the signal and then cut the string, when the dispenser fires, you get a crash. I've attached the crashlog to this post. If there is anything else I can do, please let me know.

Take care,
Chronosacaria

[crash-2021-08-27_16.10.18-server.txt](https://github.com/Globox1997/Dehydration/files/7069225/crash-2021-08-27_16.10.18-server.txt)

**Comment by Globox1997** [comment]
Thanks for the report, fixed with [https://github.com/Globox1997/Dehydration/commit/0ca7dd22ce81b49911daf41c6c6338d2df3c4160](https://github.com/Globox1997/Dehydration/commit/0ca7dd22ce81b49911daf41c6c6338d2df3c4160)
