### ISSUE TITLE
Blazeborns are forced to drink water.

### ISSUE THREAD

**Issue by toErIpNid** [Globox1997/Dehydration#44]
As a Blazeborn I cannot drink the sensible liquid such as lava, this mod forces me to drink vessels full of that poison liquid called water. Please stop this abuse. 

TLDR: Incompatibility with the Origins mod. It forces nether origins such as blazeborn to drink water, which can be extremely problematic given the nether doesn't have any.

**Comment by Globox1997** [comment]
Is fixed with the latest version, but it is a cheaper solution cause those players just get added to the excluding list
