### ISSUE TITLE
Dispenser issue Crash

### ISSUE THREAD

**Issue by SharkieTV** [Globox1997/Dehydration#45]
Some reason it crashes when flipping a lever on a dispenser and removing Dehydration fixes it
https://pastebin.com/PJS7ixA5

**Comment by Globox1997** [comment]
Thanks for reporting this issue, fixed with [https://github.com/Globox1997/Dehydration/commit/0ca7dd22ce81b49911daf41c6c6338d2df3c4160](https://github.com/Globox1997/Dehydration/commit/0ca7dd22ce81b49911daf41c6c6338d2df3c4160)
