### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by colby-boucher** [Globox1997/Dehydration#46]
I was about to suggest that a way to automate water purification should be implemented- but lo and behold, despite it not working with normal cauldrons, you can use a bucket of water in a dispenser to fill campfire cauldrons. 100% automated water system, just need lots of buckets.

Point is, I really think it should be documented somewhere that this functionality exists, because I think it's *really* significant that it can be automated by in a totally vanilla way.

**Comment by Globox1997** [comment]
Yea it should be documented somewhere, I'm just too lazy xD

**Comment by Globox1997** [comment]
There is now some documentation with a handbook added by patchouli.
It doesn't add the info for how to automate purification but general info which is imo enough.
