### ISSUE TITLE
Crash when using dynocap on cauldron block

### ISSUE THREAD

**Issue by SattesKrokodil** [Globox1997/Dehydration#48]
https://pastebin.com/aTcq8PYZ

Hey Globox! 

I've been told by the dynocap dev that this is most likely a bug on your side.

Wish you a very nice day (=

**Version: 1.17.1**
**Dehydration 1.2.2**

**Comment by Globox1997** [comment]
Thanks for the report, fixed with [https://github.com/Globox1997/Dehydration/commit/a92f2044b8885952e6ca4ce094bc42ad0f0d30c5](https://github.com/Globox1997/Dehydration/commit/a92f2044b8885952e6ca4ce094bc42ad0f0d30c5)
