### ISSUE TITLE
[bug] dehydration ui invisible after update to 1.2.2 or later

### ISSUE THREAD

**Issue by TobiPeterG** [Globox1997/Dehydration#49]
Hey there,

I noticed that the dehydration HUD (the water drooplets over the hunger bar) is invisible (in about 9/10 cases) after updating to version 1.2.2 or later.
I'm playing on a private server, so not in a singleplayer world, don't know if this is relevant

**Comment by Globox1997** [comment]
Do you play or played with a mod called Origins?
Does it happen when Dehydration only is installed?

**Comment by TobiPeterG** [comment]
> Do you play or played with a mod called Origins?
> Does it happen when Dehydration only is installed?

Yes, I play with Origins and it doesn't happen with just dehydration installed

**Comment by IrateApathete** [comment]
Having this same issue.

**Comment by Kaosu99** [comment]
if you go into mod menu config scroll to bottom where it says excluded names and remove yourself from that list it should bring it back

**Comment by Globox1997** [comment]
Removed the excluding list in version 1.2.4 which should fix this issue :)
I added a command to disable thirst on players
