### ISSUE TITLE
Dehydration Hot Symbol not showing in desert

### ISSUE THREAD

**Issue by PalgamingHD** [Globox1997/Dehydration#5]
Title says it all, the only mods I have installed are jumploader and fabric API

**Comment by Globox1997** [comment]
Does this happen in survival mode?

**Comment by PalgamingHD** [comment]
Yes

**Comment by Globox1997** [comment]
are you using version 1.0.8?

**Comment by PalgamingHD** [comment]
Yea, latest version from curseforge

**Comment by Globox1997** [comment]
mh thats quite weird cause I can't reproduce this bug

**Comment by PalgamingHD** [comment]
That's wierd. It's happening in any instance I'm using. I teleport to a desert in creative mode, go into survival, walk around to try to get the symbol, and even after 5min there's still nothing.

**Comment by Globox1997** [comment]
mh since I can't reproduce the bug I would close this issue

**Comment by PalgamingHD** [comment]
alright, i'll see if my friends have the same issue

**Comment by Globox1997** [comment]
okay I'll leave it open until you asked them :)

**Comment by PalgamingHD** [comment]
Sorry for taking so long to respond
[https://cdn.discordapp.com/attachments/461619440115646464/794326770690162698/2020-12-31_16.09.01.png](url)
Yea its happening to other people as well, as well as other computers I have, same exact mods list. I'm not sure if this is intended or not. I ran around for a couple minutes and still no heat symbol.

**Comment by Globox1997** [comment]
no it's definitely not intended

**Comment by Globox1997** [comment]
any hud mods installed?

**Comment by PalgamingHD** [comment]
None, I only had Jumploader and Fabric Api

**Comment by Globox1997** [comment]
The overheating effect (and the indicating flame symbol) will only show up while you are overheating which happens when every following condition applies at the same time: staying in hot biomes + wearing at least on piece of armor + sky/sun is visible + daytime + no hydrating enchantment

**Comment by PalgamingHD** [comment]
Got it, thanks!
