### ISSUE TITLE
Campfire Cauldrons turn to normal cauldrons and crash the instance after use

### ISSUE THREAD

**Issue by DaFuqs** [Globox1997/Dehydration#51]
While playing on the Anima modpack today I saw that my campfire cauldron was turned to a default vanilla cauldron. Using a flask on that cauldron (or any other cauldron, for that matter), crashed my client.

Crashlog: https://pastebin.com/LNTa704x

Pinging @SattesKrokodil, too, since it happened on the Anima modpack.

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/Dehydration/commit/a8f61a784bb3a0968b28de093cfd64f528fcc9a8](https://github.com/Globox1997/Dehydration/commit/a8f61a784bb3a0968b28de093cfd64f528fcc9a8)

**Comment by Globox1997** [comment]
Please close this issue if version 1.2.4 fixes it
