### ISSUE TITLE
Add Ability to move HUD Elements

### ISSUE THREAD

**Issue by CloudTheWolf** [Globox1997/Dehydration#53]
As a mod pack created I would like the be able to move the Hydration HUD so that it does not overlap other HUD Elements.

This could either be a Config file object or take advantage of the HUDTweaks API.

**Comment by Globox1997** [comment]
Added it with [https://github.com/Globox1997/Dehydration/commit/177e8786ee03bb7492807beae8afa27db2cb8904](https://github.com/Globox1997/Dehydration/commit/177e8786ee03bb7492807beae8afa27db2cb8904)
