### ISSUE TITLE
Update ModMenu Link

### ISSUE THREAD

**Issue by Lorelando** [Globox1997/Dehydration#55]
Opening the website link in ModMenu leads to https://www.curseforge.com/minecraft/mc-mods/hydration.
It should be https://www.curseforge.com/minecraft/mc-mods/dehydration.

**Comment by Globox1997** [comment]
Thanks for reporting it, fixed with [https://github.com/Globox1997/Dehydration/commit/3de6d5ec7cd756d88428d9fbf4b6ef7b2ddddbfa](https://github.com/Globox1997/Dehydration/commit/3de6d5ec7cd756d88428d9fbf4b6ef7b2ddddbfa)
