### ISSUE TITLE
Incompatibility with origins mod

### ISSUE THREAD

**Issue by ekiplier** [Globox1997/Dehydration#56]
The problem is that when someone with the Enderian Origin tries to drink from a water bottle, they get damaged, which is a bit counter-productive. Also, Merlins shouldn't really have to drink water as they're already constantly underwater. Can there be an exception to disable dehydration for players who choose such origins? Thanks in advance :)

**Comment by Globox1997** [comment]
Yes, there is a command for making players have dehydration :)

**Comment by ekiplier** [comment]
Oh! Well, is there a way modpack devs can run that command automatically for when players choose that origin? Also, did you mean "for making players NOT have dehydration"? thanks

**Comment by Globox1997** [comment]
That is a good question, I don't know.

**Comment by KuwuroUsagi** [comment]
> is there a way modpack devs can run that command automatically for when players choose that origin?

basically globox would have to add a config option specifically for blacklisting specific origins from having dehydration so modpack devs could adjust it, otherwise players or admins will just have to handle it case by case
 assumedly

**Comment by Globox1997** [comment]
There is already compatibility with [https://github.com/Globox1997/Dehydration/blob/1.18/src/main/java/net/dehydration/mixin/compat/PlayerOriginComponentMixin.java](https://github.com/Globox1997/Dehydration/blob/1.18/src/main/java/net/dehydration/mixin/compat/PlayerOriginComponentMixin.java)

**Comment by Globox1997** [comment]
With the command callback [https://origins.readthedocs.io/en/latest/types/power_types/action_on_callback/](https://origins.readthedocs.io/en/latest/types/power_types/action_on_callback/) you can set the players hydration with /thirst playername false
