### ISSUE TITLE
Dying in multiplayer visually breaks Thirst Bar

### ISSUE THREAD

**Issue by Kenocrystal** [Globox1997/Dehydration#57]
Dying in multiplayer visually breaks Thirst Bar and causes the thirst bar to not display information correctly. I've had this issue for awhile in many multiplayer servers on different versions and it is really inconvenient. The bar could say that you're perfectly fine but you could still be dying due to it actually being empty but not displaying correctly. It happens sometimes (very very rarely) in singleplayer worlds too and is sometimes extremely annoying. Leaving and rejoining or closing and reopening your world could fix it, but it is still really annoying to deal with. 

1.17.1
dehydration-1.2.5 : Dehydration

**Comment by Globox1997** [comment]
this happens after the player died? before everything works fine?

**Comment by Kenocrystal** [comment]
> this happens after the player died? before everything works fine?

yes

**Comment by Globox1997** [comment]
Can't reproduce this bug... When the player dies, the thirst bar should be full again, is that the case?

**Comment by Kenocrystal** [comment]
It should be, I don't know why you aren't getting it

**Comment by Globox1997** [comment]
Latest update should have fixed it with [https://github.com/Globox1997/Dehydration/commit/d003cb07a1f0cb1af89e9e3b6fdeca85c2eaa367](https://github.com/Globox1997/Dehydration/commit/d003cb07a1f0cb1af89e9e3b6fdeca85c2eaa367)
