### ISSUE TITLE
(1.18) dehydration (and also environmentZ) crash with origins (1.18 compiled from repo) when starting a world

### ISSUE THREAD

**Issue by SweepSwap** [Globox1997/Dehydration#58]
when starting a world, the game crashes, i have not enough crashes so that minecraft doesn't close
heres a log from multimc https://paste.ee/p/FbCeA

**Comment by SweepSwap** [comment]
when either environmentz and dehydration or origins are not installed it doesn't crash

**Comment by Globox1997** [comment]
When either one of those three mods is not installed, it doesn't crash?
I don't find anything specific in the crash log, checked the mixin and it works fine.
can you get a crash without dehydration?

**Comment by SweepSwap** [comment]
heres a crash when only the fabric api, environmentz, and origins are installed
https://paste.ee/p/cU7aG

**Comment by Globox1997** [comment]
I've seen you are using mc 1.18 already, today it will get released officially :) might fix the issue

**Comment by SweepSwap** [comment]
I've been using 1.18 since 21w44a since i love the new terrain generation and being able to use mods on a version before the official release is a pretty cool for me.

**Comment by SweepSwap** [comment]
nope, still doesn't work on 1.18 loader 12.8
The game crashed whilst starting integrated server
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3324 failed
Exit Code: -1

**Comment by Globox1997** [comment]
Trying to contact the dev of origins

**Comment by SweepSwap** [comment]
any luck?

**Comment by Globox1997** [comment]
So talked to Apace (dev of origins) and we couldn't figure out what causes this..
Will stay open until it get fixed somehow

**Comment by LilyLicht** [comment]
I don't seem to have this issue.

**Comment by Globox1997** [comment]
[dehydration-1.2.6.zip](https://github.com/Globox1997/Dehydration/files/7784468/dehydration-1.2.6.zip)
@SweepSwap could you test this?

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/Dehydration/commit/727c75526ee0e8a1b587b21a9bc754aca7c78299](https://github.com/Globox1997/Dehydration/commit/727c75526ee0e8a1b587b21a9bc754aca7c78299)
Reopen if still happening
