### ISSUE TITLE
AppleSkin-style feature?

### ISSUE THREAD

**Issue by LeeroyGarfield** [Globox1997/Dehydration#59]
Would it be possible for you to add an [AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin)-style mechanic into Dehydration? Although [WaterSkin](https://www.curseforge.com/minecraft/mc-mods/waterskin) exists, it's been stuck in 1.12 for ages. Make it a toggle option as well, in case certain people don't like it. I, on the other hand, would love it!

**Comment by Globox1997** [comment]
Added with latest update
