### ISSUE TITLE
Some suggestions/ideas

### ISSUE THREAD

**Issue by Xetheon** [Globox1997/Dehydration#6]
Hi! I like this mod quite a bit and have been working on a modpack with it, which is why a few ideas came up while playing around with it

It would be really neat to see more data-driven aspects added to add some more interesting possibilities. The ability to adjust how exactly heat can effect the player is one: Biome-specific heat levels, blocks that have a radius of making the player colder/hotter, certain y levels where the temperature varies, that kind of thing. As with the thirst aspect, more control over foods/items that give a specific amount of water when consumed is an idea.

Direct compat with Fabric Seasons in some way could be very cool as well, maybe by adding another layer of heat reduction/addition based on what season is active? 

Anyway, that's about all that I can think of. Most of that would also be nice to have in your environment-z mod too, but again it's only suggestions! I understand how doing all that isn't just a walk in the park, but seeing any of those features added would be awesome

**Comment by Gappysona** [comment]
Heat mechanics are being moved to EnvironmentZ and will have finer control to its temperature aspects

**Comment by RDKRACZ** [comment]
@Gappysona maybe it would be better to merge Dehydration and Environmentz into one mod? Forge mods like Tough as Nails or Survive combine both these functionalities.

**Comment by Gappysona** [comment]
Because most people will likely only want the thirst mechanic or the heat/freeze mechanic rather than both

**Comment by RDKRACZ** [comment]
Well, you can just disable mechanics if you don't want it. The point of dehydration and environments is similar - make the game harder by adding some realism. Having all these mechanics in one mod should be easier to maintain but what do I know about it. I only use the ready product.

**Comment by Globox1997** [comment]
It would be more easy to develop the mod yes but I think it's fine :) Not a bad idea tho ^^

**Comment by Globox1997** [comment]
So environment aspects moved to environmentz.
