### ISSUE TITLE
Suggestion: Buff flasks to hold more water

### ISSUE THREAD

**Issue by LilyLicht** [Globox1997/Dehydration#63]
Leather: 4
Iron: 8
Gold: 16
Diamond: 32
Netherite: 64

Reason: You can hold 64 food items in a single slot. So Dehydration feels a bit tedious in comparison with it's current config.

Example: If I want to go for a base relocation trip, a single stack of food would be enough, but I'd need half an inventory full of diamond / netherite flasks.

**Comment by Globox1997** [comment]
hey Lily, that doesn't really fit with my vision for this mod but I added a config to increase the size of the flasks with [https://github.com/Globox1997/Dehydration/commit/6660ccedf7a2909993c8b339de9e2e41c62dcbfb](https://github.com/Globox1997/Dehydration/commit/6660ccedf7a2909993c8b339de9e2e41c62dcbfb)

**Comment by LilyLicht** [comment]
Thanks for investing the time for me, it says a lot about you as a dev! :+1:

**Comment by Globox1997** [comment]
thank you too :)
pretty dope sweater your profile pic wears :D did you draw that?
