### ISSUE TITLE
Game crashes when loading world in 1.18

### ISSUE THREAD

**Issue by Givoric** [Globox1997/Dehydration#64]
From what i have read in the log it seems to be an issue with dehydration mixins. If it is not like that i apologise
crash log: https://pastebin.com/pyFG2DxA

**Comment by 0x6273** [comment]
This is a duplicate of #58. You'll have to pick either Dehydration or Origins. In 1.18 they are not compatible.

**Comment by Globox1997** [comment]
Referencing #58
