### ISSUE TITLE
Origin's UI overlapping Dehydration's UI

### ISSUE THREAD

**Issue by theDerxu** [Globox1997/Dehydration#65]
(I am using my own origin that is a datapack)
![image](https://user-images.githubusercontent.com/88974734/147860254-2b1532a6-7551-47c2-8e95-8db64281f28d.png)
The thirst bar seems to cover the soul bar rather than stacking them.

**Comment by Globox1997** [comment]
Check out the advanced config settings, there you can adjust the position of the thirst bar :)

**Comment by theDerxu** [comment]
Thanks but how do I find the config? I am using a lot of mods so I can only see config through the files.

**Comment by Globox1997** [comment]
I recommend to use modmenu, to change the settings while in game

**Comment by theDerxu** [comment]
alright. I'll try that. :)
