### ISSUE TITLE
[1.18.1] Copper Campfire Cauldron randomly transforms into Iron Cauldron

### ISSUE THREAD

**Issue by lizfinite** [Globox1997/Dehydration#66]
https://www.youtube.com/watch?v=FnpUd-KTTc4
Here's a video of it happening while I was running by. Happens right at the end of the video. 

I can provide logs if you like, but they're full of other spam from other mods, so I'm going to try and recreate the issue with just dehydration installed and get a clean log with just it and dependencies.

**Comment by Globox1997** [comment]
Thanks for the good report even with a video :D 
Fixed with [https://github.com/Globox1997/Dehydration/commit/259c1a2ce812cba17286044d4443e6335837d1ff](https://github.com/Globox1997/Dehydration/commit/259c1a2ce812cba17286044d4443e6335837d1ff)
