### ISSUE TITLE
Purifying with Copper Cauldron

### ISSUE THREAD

**Issue by KuwuroUsagi** [Globox1997/Dehydration#68]
Unsure if something similar is implemented already, but being able to purify with the copper cauldron as opposed to just the campfire cauldron would be very convenient.
Whether it's with campfire underneath, lit netherrack, a magma block or lava source etc.

**Comment by Globox1997** [comment]
Not a bad idea but I have no plans to add such a feature to the copper cauldron.
You can fill up the copper cauldron with purified water by a stalactites tho.
