### ISSUE TITLE
[Mod compat] drinks from Croptopia should fill thirst bar from Dehydration.

### ISSUE THREAD

**Issue by RDKRACZ** [Globox1997/Dehydration#7]
Reported to Croptopia too - https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/26

**Comment by Globox1997** [comment]
Can be done very easily.
Croptopia dev just have to add the drinks to the hydrating_drinks tag

**Comment by Globox1997** [comment]
Not 100% sure but I think  the croptopia dev added compatibility

**Comment by RDKRACZ** [comment]
This should be working right? It's not.
