### ISSUE TITLE
Make this mod all every modder whants on fabric!

### ISSUE THREAD

**Issue by VoltHertz** [Globox1997/Dehydration#71]
Please, make that copper cauldron fill with water from driping stones, actualy in real life, water from drip stones are very pure, so we could make it drip on copper cauldrons to get pure water... at the same time please make water bottle and purified water bottle stack to 8.
And please dont forget to make water bottle get purified by putting them on a furnus...

All these ideas exists in other thisty mods for forge... they are more like real life, thanks.

**Comment by Globox1997** [comment]
This feature got added in a later update I think.
