### ISSUE TITLE
Extra Tags

### ISSUE THREAD

**Issue by Laifsyn** [Globox1997/Dehydration#78]
Add Tags for Extra milk(ehem, malusphaethusa mod or milk+) and or 'hyper-hydrating' food and or drinks so they can be added through datapacks

**Comment by Globox1997** [comment]
Added stronger tags with [https://github.com/Globox1997/Dehydration/commit/ef808d3a0f14f213531876c478804685b02c0679](https://github.com/Globox1997/Dehydration/commit/ef808d3a0f14f213531876c478804685b02c0679)
