### ISSUE TITLE
Config and drink tag mixup

### ISSUE THREAD

**Issue by Laifsyn** [Globox1997/Dehydration#79]
`"potion_thirst_quench"` besides affecting the potions, it also affects what's written in the `hydrating_drinks.json` . idk if it's intended

**Comment by Globox1997** [comment]
Yes that is intended but for clarity I added a separate config setting with [https://github.com/Globox1997/Dehydration/commit/c4dd29b7f66a25e424734565d969e50c4d4bd1f7](https://github.com/Globox1997/Dehydration/commit/c4dd29b7f66a25e424734565d969e50c4d4bd1f7)
