### ISSUE TITLE
[SUGGESTION] Compat with Haema and Bewitchment vampires

### ISSUE THREAD

**Issue by Sunconure11** [Globox1997/Dehydration#80]
Since both suck blood... could there be some kind of option for these two mods to allow vampires and similar creatures to use blood to fulfill thirst?

**Comment by Globox1997** [comment]
Dehydration provides an api to gain thirst on an event :)

**Comment by williambl** [comment]
> Dehydration provides an api to gain thirst on an event :)

thank you :)

**Comment by Sunconure11** [comment]
@Globox1997 Please see issue #99, I think it may be better for you to do it on your end, with the reasoning I gave for BW.

**Comment by Sunconure11** [comment]
Does Environmentz have a similar API, but for temp?

**Comment by Globox1997** [comment]
You can adjust the players temperature by code of course.
#99
