### ISSUE TITLE
Compatibility with origin mod

### ISSUE THREAD

**Issue by TheeMrCheeky** [Globox1997/Dehydration#82]
So when in nether as blazeborn class from the origins mod your water bar is there and isn't there at times of death or reloading the world. 
![image](https://user-images.githubusercontent.com/96976998/166613525-0c7276cb-725b-4cba-990e-142d4c53a77a.png)

fabric 0.14.0
mc version 1.18.2

**Comment by TheeMrCheeky** [comment]
ALSO could add maybe drinking from rain to replenish thirst? Just a idea

**Comment by Globox1997** [comment]
There is already compat with origins, if the origin has fire immunity it doesn't have a thirst mechanic.
With the command callback provided by origins you can set the thirst mechanic on and off too.
The second idea is not something I consider but you can drink from water source blocks :)
