### ISSUE TITLE
Croptopia Compatibility Broken

### ISSUE THREAD

**Issue by RitualSSB** [Globox1997/Dehydration#83]
Croptopia compatibility has been broken by their new 2.0 update. I left an issue on their author's page (linked [Here](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/372): ) as well.

**Comment by MScott7** [comment]
I'm having the same issue, as is this curseforge commenter who provided a crash log that looks very similar to mine: https://www.curseforge.com/minecraft/mc-mods/dehydration?comment=267 ([their pastebin link](https://pastebin.com/sd5hfmfb)).

**Comment by HyperlyBola** [comment]
I recommend using Croptopia 1.8.3 until the new update is fixed

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/tpzlpuYotd

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/Dehydration/commit/906eeafab84f8698971a2dcc0900cd9bd291a14d](https://github.com/Globox1997/Dehydration/commit/906eeafab84f8698971a2dcc0900cd9bd291a14d)
