### ISSUE TITLE
Suggestion for flask>cauldron behavior

### ISSUE THREAD

**Issue by TheMightyMcGrew** [Globox1997/Dehydration#84]
Currently players can add water to the cauldron with glass water bottles and buckets but are unable to with any flask. It would be nice to be able to add water with your flasks.

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/Dehydration/commit/3cd9de4aa6e36d9dc03a788b36edfaf6d4ecfef3](https://github.com/Globox1997/Dehydration/commit/3cd9de4aa6e36d9dc03a788b36edfaf6d4ecfef3)
