### ISSUE TITLE
Mixin error between this and Wilder World

### ISSUE THREAD

**Issue by Sunconure11** [Globox1997/Dehydration#88]
https://pastebin.com/jZv9AtZS

**Comment by Globox1997** [comment]
The main error is cause of an issue of oxidized mod but I fixed the incompat with wilder world with [https://github.com/Globox1997/Dehydration/commit/d2663656700a6cc265d380af90fbe640473ffe4d](https://github.com/Globox1997/Dehydration/commit/d2663656700a6cc265d380af90fbe640473ffe4d)
