### ISSUE TITLE
Show hydration on all kinds of food/stew/water glass...etc on UI

### ISSUE THREAD

**Issue by Bo-Hsiung** [Globox1997/Dehydration#89]
Please show how many hydration can be restore on those items and add some other foods to hydration list by editing config file

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/Dehydration/commit/478e829466c14bc4f17c987be1af88c02348552e](https://github.com/Globox1997/Dehydration/commit/478e829466c14bc4f17c987be1af88c02348552e)
