### ISSUE TITLE
Cannot fill a partially empty flask.

### ISSUE THREAD

**Issue by MokkaCicc** [Globox1997/Dehydration#9]
We currently cannot fill a partially empty flask. We must fully empty it to fill it with water. I think letting us filling it whenever we want would be better!

**Comment by Globox1997** [comment]
Fixed [https://github.com/Globox1997/Dehydration/commit/03bc0c60d8a6382a87796ee1c2bfbac0f2767e9c](https://github.com/Globox1997/Dehydration/commit/03bc0c60d8a6382a87796ee1c2bfbac0f2767e9c)
