### ISSUE TITLE
Accept Modded Campfire/Stove for Campfire Cauldron

### ISSUE THREAD

**Issue by ardissaps** [Globox1997/Dehydration#91]
Thank you very much!

- [BYG](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric) Campfires
- [FarmersDelight](https://www.curseforge.com/minecraft/mc-mods/farmers-delight) Stove

Also would be greate if placable Copper Cauldron water can be dyed like [CauldronDyeing](https://modrinth.com/mod/cauldron-dyeing).
https://github.com/TibiNonEst/cauldron-dyeing/issues/5

**Comment by Globox1997** [comment]
BYG has to add their campfires to the vanilla tag called "campfires", then it will work with them.
