### ISSUE TITLE
extra_flask_size in dehydration.json5 does not seem to effect flask capacity in multiplayer server

### ISSUE THREAD

**Issue by Coyote21** [Globox1997/Dehydration#93]
I'm using a heavily modded 1.18.2 fabric server. One of the mods allows for potion stacking meaning that bottles of purified water can now be stacked to 16 bottles.

This makes the flasks, which can not be stacked, a serious downgrade from using bottles. To compensate I tried to increase the capacity of the flasks to match a stack of water bottles (16 Drops) but no matter what integer I put into "extra_flask_size" in dehydration.json5 on both server and client, the capacity of the flasks did not change.

I have tried values for  "extra_flask_size" from 2 to 20 using the following format - ```"extra_flask_size": 2,```

BTW, I'm using ```"extra_flask_size": 2,``` b/c ```"flask_thirst_quench": 4,``` (default) so having 4 (2 + 2) charges on the leather flask = 16 drops

I have tried destroying all flasks in my inventory, shutting down server, changing config value, restarting server and remaking the flasks, no change to flask capacity.

Am I mis-understanding how this value is supposed to be implemented in game?

Any help would be appreciated.

**Comment by Globox1997** [comment]
I can confirm the extra flask size config doesn't work so I removed it with [https://github.com/Globox1997/Dehydration/commit/a88d001e964ba7323c6a8b6431558169fbd93cc1](https://github.com/Globox1997/Dehydration/commit/a88d001e964ba7323c6a8b6431558169fbd93cc1)
Increasing the thirst quench of the flask should work
