### ISSUE TITLE
Suggestion: Add compatibility for Farmer's Delight

### ISSUE THREAD

**Issue by Sugmaballs24** [Globox1997/Dehydration#94]
The drinks: Melon juice, apple cider, hot cocoa

Would be nice

**Comment by Globox1997** [comment]
Looks like farmers delight added compat with [https://github.com/newhoryzon/farmers-delight-fabric/commit/3faf3b4532225fbcd8fae4ab0ce61b28aaf3e54f](https://github.com/newhoryzon/farmers-delight-fabric/commit/3faf3b4532225fbcd8fae4ab0ce61b28aaf3e54f)
