### ISSUE TITLE
Anaku's Status Bars Support

### ISSUE THREAD

**Issue by ardissaps** [Globox1997/Dehydration#95]
Would you please support [Anaku's Status Bars](https://github.com/LordAnaku/Anakus_Status_Bars/issues/2)? Thank you verymuch

**Comment by Globox1997** [comment]
Reference [https://github.com/LordAnaku/Anakus_Status_Bars/issues/2](https://github.com/LordAnaku/Anakus_Status_Bars/issues/2)

**Comment by Globox1997** [comment]
For now I have no plans to add compatibility on my side, open for a PR.
