### ISSUE TITLE
Incompatibility with Bewitchment 

### ISSUE THREAD

**Issue by SHXRKIEgg** [Globox1997/Dehydration#99]
When becoming a Vampire with Bewitchment the hunger bar still stays and does not turn into blood droplets. So when turning into a Vampire your hunger bar stays full forever so you are never hungry and cant drink blood since you are always "full".

Using:
bewitchment-1.19-5.jar
dehydration-1.2.10.jar

**Comment by Sunconure11** [comment]
https://github.com/Globox1997/Dehydration/issues/80

@Globox1997 Can you implement support on your end? The devs of BW aren’t exactly interested in vampires and such, mostly because players bumrush to them. They are also making a separate mod as well for transformations that is far more fleshed out.

**Comment by Globox1997** [comment]
Not sure if I understand it correctly but "hunger" should turn into blood droplets?

**Comment by SHXRKIEgg** [comment]
Yeah so when turning into a Vampire with the bewitchment ritual, the hunger bar is supposed to be replaced by BLood Droplets from the bewitchment mod but it does not instead it keeps the hunger bar causing issues with trying to drink blood.

**Comment by SimoVolkihar** [comment]
> Not sure if I understand it correctly but "hunger" should turn into blood droplets?

Wouldn't it be easy to just disable hydration system on vampires? as long as they already drink blood.

**Comment by Sunconure11** [comment]
Well, the current dev of BW is going through some stuff. I strongly suggest you put this fix on your end, because the dev won't do it on his end @SimoVolkihar @Globox1997

**Comment by Globox1997** [comment]
I have no plans to add compatibility to bewitchment lately. Might change in the future but chances are low.
